/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.newproject.johnathan;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void add() {
        App classUnderTest = new App();
        int inputNumber;
        inputNumber = 1;
        assertNotNull(classUnderTest.addUpNumber(inputNumber), "app should have a greeting");
    }
}
