/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.newproject.johnathan;

public class App {
    public int addUpNumber(int inputNumber) {
        return inputNumber;
    }

    public static void main(String[] args) {
        int inputNumber;
        inputNumber = 1;
        
        System.out.println(new App().addUpNumber(inputNumber));
    }
}
